v = input('Digite algo = ')
print('O tipo dessa váriavel é', type(v))
print('Só tem espaços?', v.isspace())
print('É um número?', v.isnumeric())
print('É alfabético?', v.isalpha())
print('É alfanumérico?', v.isalnum())
print('Está em letras maiúsculs?', v.isupper())
print('Está em letras minúsculas?', v.islower())
print('Está capitalizada?', v.istitle())
